# Generated by Django 4.2.5 on 2023-10-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tags_review_projects_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
